clean downloads updated

diff --git a/Applications/clean_downloads b/Applications/clean_downloads
--- a/Applications/clean_downloads
+++ b/Applications/clean_downloads
@@ -1,9 +1,30 @@
 #!/bin/bash
-if ! command -v trash &> /dev/null
+
+if ! command -v fd &> /dev/null
   then
-    rm -rf ~/Downloads/*
-    echo "used rm command"
-  else
-    trash ~/Downloads/*
-    echo "used trash command"
+    echo "##############################################"
+    echo "fd command not found -- terminating."
+    echo "##############################################"
+    exit 1
+elif ! command -v fd &> /dev/null
+  then
+    echo "##############################################"
+    echo "trash command not found -- terminating."
+    echo "##############################################"
+    exit 1
+else
+    echo "##############################################"
 fi
+
+DL=~/Downloads
+
+if [[ `fd . $DL --prune | wc -l` -gt 0 ]]
+  then
+    fd . $DL --prune --no-ignore-vcs -X trash
+    echo "- Cleaned `basename $DL`."
+    trash -e
+  else
+    echo "`basename $DL` is already empty."
+fi
+
+echo "##############################################"
